apiVersion: v1
kind: Pod
metadata:
  name: vini-app-nodejs
  labels:
    app: vini-app-nodejs
spec:
  containers:
    - name: container-pod-nodejs
      image: didox/app-nodejs-validacao-cnpj
      ports:
        - containerPort: 3000

# kubectl apply -f pod-nginx.yml
# kubectl describe -f pod-nginx.yml
# kubectl delete -f pod-nginx.yml
