apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodejs-replicaset
spec:
  template:
    metadata:
      name: vini-app-nodejs
      labels:
        app: vini-app-nodejs
    spec:
      containers:
        - name: container-pod-javadb
          image: didox/app-nodejs-validacao-cnpj
          # env:
          #   - name: USER
          #     value: root
          #   - name: PASSWORD
          #     value: password_mysql
          #   - name: DATABASE_URL
          #     value: mysql://mysql:3306/SpringWebYoutubeTest?useTimezone=true&serverTimezone=UTC
          #     # value: mysql://10.111.41.255:3306/SpringWebYoutubeTest?useTimezone=true&serverTimezone=UTC
          # ports:
          ports:
            - containerPort: 3000
  replicas: 3
  selector:
    matchLabels:
      app: vini-app-nodejs


# $ kubectl logs -l app=lable-pod-java # log de todos os lables do replicaset
# $ kubectl logs --tail=20 --follow=true -l app=lable-pod-java