apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap-prod
data:
  USER: $USER
  PASSWORD: $PASSWORD
  DATABASE_URL: mysql://$PROD:3306/$DATABASE?useTimezone=true&serverTimezone=UTC
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment-prod
spec:
  template:
    metadata:
      name: pod-javadb-prod
      labels:
        app: pod-javadb-prod
    spec:
      containers:
        - name: container-pod-javadb-prod
          image: vinigim/crud-java-login:v0.0.1
          env:
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap-prod
                  key: USER
            - name: PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap-prod
                  key: PASSWORD
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap-prod
                  key: DATABASE_URL
          ports:
            - containerPort: 8080
  replicas: 2
  selector:
    matchLabels:
      app: pod-javadb-prod
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-pod-javadb-prod
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001 # 30000 ~ 32767
  selector:
    app: pod-javadb-prod