image: docker

stages:
- pre-build
- build
- test
- deploy

before_script:
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build:
  services:
  - docker:dind
  - openjdk
  # - maven:3-jdk-8

  before_script:
  - ./mvnw package

  # tags: # executor de tarefas em minha maquina
  # - executor-tarefa-java

  stage: pre-build
  script:
  - docker build -t didox/validador-cpf-java-turma-devops -f Dockerfile .
  - docker tag didox/validador-cpf-java-turma-devops hub.docker.com/r/didox/validador-cpf-java-turma-devops
  - docker push didox/validador-cpf-java-turma-devops

build-project:
  stage: build
  dependencies:
  - build
  script:
  - echo "teste"


# para acessar a imagem docker e configurar o servidor de build
# $ docker exec -it gitlab-runner bash
