# imagem docker com java
image: docker:stable
# image:  bitsdock/docker-java-sbt

# verifica se temos ao docker
services:
- docker:dind

before_script:
- docker info
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
# dentro do gitlab para colocar as variáveis
# https://gitlab.com/Didox/ci-cd-java-app-treinamento/-/settings/ci_cd
# item Variables
# adicionar seu user e pass

build:
  stage: build
  script:
  # como colocar tag no docker https://docs.docker.com/engine/reference/commandline/push/
  - docker build -t didox/validador-cpf-java-turma-devops:v0.0.2 -f Dockerfile .
  # - docker tag didox/validador-cpf-java-turma-devops:v0.0.1 hub.docker.com/r/didox/validador-cpf-java-turma-devops:v0.0.1
  - docker push didox/validador-cpf-java-turma-devops:v0.0.2